# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='polkaAutomator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\x12\x0epolkaAutomator\"\x07\n\x05\x45mpty\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x10ShowPathsRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\"D\n\x11ShowPathsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05paths\x18\x02 \x03(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"B\n\x11\x43onfigPathRequest\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t2\x83\x03\n\x15PolkaAutomatorService\x12?\n\x0cStartNetwork\x12\x15.polkaAutomator.Empty\x1a\x18.polkaAutomator.Response\x12>\n\x0bStopNetwork\x12\x15.polkaAutomator.Empty\x1a\x18.polkaAutomator.Response\x12P\n\tShowPaths\x12 .polkaAutomator.ShowPathsRequest\x1a!.polkaAutomator.ShowPathsResponse\x12O\n\x10\x43onfigSinglePath\x12!.polkaAutomator.ConfigPathRequest\x1a\x18.polkaAutomator.Response\x12\x46\n\x13\x43onfigShortestPaths\x12\x15.polkaAutomator.Empty\x1a\x18.polkaAutomator.Responseb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='polkaAutomator.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=40,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='polkaAutomator.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='polkaAutomator.Response.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='polkaAutomator.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=86,
)


_SHOWPATHSREQUEST = _descriptor.Descriptor(
  name='ShowPathsRequest',
  full_name='polkaAutomator.ShowPathsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='polkaAutomator.ShowPathsRequest.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='polkaAutomator.ShowPathsRequest.target', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=138,
)


_SHOWPATHSRESPONSE = _descriptor.Descriptor(
  name='ShowPathsResponse',
  full_name='polkaAutomator.ShowPathsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='polkaAutomator.ShowPathsResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paths', full_name='polkaAutomator.ShowPathsResponse.paths', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='polkaAutomator.ShowPathsResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=208,
)


_CONFIGPATHREQUEST = _descriptor.Descriptor(
  name='ConfigPathRequest',
  full_name='polkaAutomator.ConfigPathRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='polkaAutomator.ConfigPathRequest.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='polkaAutomator.ConfigPathRequest.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='polkaAutomator.ConfigPathRequest.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=276,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ShowPathsRequest'] = _SHOWPATHSREQUEST
DESCRIPTOR.message_types_by_name['ShowPathsResponse'] = _SHOWPATHSRESPONSE
DESCRIPTOR.message_types_by_name['ConfigPathRequest'] = _CONFIGPATHREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:polkaAutomator.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:polkaAutomator.Response)
  ))
_sym_db.RegisterMessage(Response)

ShowPathsRequest = _reflection.GeneratedProtocolMessageType('ShowPathsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SHOWPATHSREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:polkaAutomator.ShowPathsRequest)
  ))
_sym_db.RegisterMessage(ShowPathsRequest)

ShowPathsResponse = _reflection.GeneratedProtocolMessageType('ShowPathsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SHOWPATHSRESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:polkaAutomator.ShowPathsResponse)
  ))
_sym_db.RegisterMessage(ShowPathsResponse)

ConfigPathRequest = _reflection.GeneratedProtocolMessageType('ConfigPathRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGPATHREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:polkaAutomator.ConfigPathRequest)
  ))
_sym_db.RegisterMessage(ConfigPathRequest)



_POLKAAUTOMATORSERVICE = _descriptor.ServiceDescriptor(
  name='PolkaAutomatorService',
  full_name='polkaAutomator.PolkaAutomatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=279,
  serialized_end=666,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartNetwork',
    full_name='polkaAutomator.PolkaAutomatorService.StartNetwork',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopNetwork',
    full_name='polkaAutomator.PolkaAutomatorService.StopNetwork',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShowPaths',
    full_name='polkaAutomator.PolkaAutomatorService.ShowPaths',
    index=2,
    containing_service=None,
    input_type=_SHOWPATHSREQUEST,
    output_type=_SHOWPATHSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConfigSinglePath',
    full_name='polkaAutomator.PolkaAutomatorService.ConfigSinglePath',
    index=3,
    containing_service=None,
    input_type=_CONFIGPATHREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConfigShortestPaths',
    full_name='polkaAutomator.PolkaAutomatorService.ConfigShortestPaths',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POLKAAUTOMATORSERVICE)

DESCRIPTOR.services_by_name['PolkaAutomatorService'] = _POLKAAUTOMATORSERVICE

# @@protoc_insertion_point(module_scope)
