# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class PolkaAutomatorServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartNetwork = channel.unary_unary(
        '/polkaAutomator.PolkaAutomatorService/StartNetwork',
        request_serializer=service__pb2.Empty.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )
    self.StopNetwork = channel.unary_unary(
        '/polkaAutomator.PolkaAutomatorService/StopNetwork',
        request_serializer=service__pb2.Empty.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )
    self.ShowPaths = channel.unary_unary(
        '/polkaAutomator.PolkaAutomatorService/ShowPaths',
        request_serializer=service__pb2.ShowPathsRequest.SerializeToString,
        response_deserializer=service__pb2.ShowPathsResponse.FromString,
        )
    self.ConfigSinglePath = channel.unary_unary(
        '/polkaAutomator.PolkaAutomatorService/ConfigSinglePath',
        request_serializer=service__pb2.ConfigPathRequest.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )
    self.ConfigShortestPaths = channel.unary_unary(
        '/polkaAutomator.PolkaAutomatorService/ConfigShortestPaths',
        request_serializer=service__pb2.Empty.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )


class PolkaAutomatorServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartNetwork(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopNetwork(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowPaths(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConfigSinglePath(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConfigShortestPaths(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PolkaAutomatorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartNetwork': grpc.unary_unary_rpc_method_handler(
          servicer.StartNetwork,
          request_deserializer=service__pb2.Empty.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
      'StopNetwork': grpc.unary_unary_rpc_method_handler(
          servicer.StopNetwork,
          request_deserializer=service__pb2.Empty.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
      'ShowPaths': grpc.unary_unary_rpc_method_handler(
          servicer.ShowPaths,
          request_deserializer=service__pb2.ShowPathsRequest.FromString,
          response_serializer=service__pb2.ShowPathsResponse.SerializeToString,
      ),
      'ConfigSinglePath': grpc.unary_unary_rpc_method_handler(
          servicer.ConfigSinglePath,
          request_deserializer=service__pb2.ConfigPathRequest.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
      'ConfigShortestPaths': grpc.unary_unary_rpc_method_handler(
          servicer.ConfigShortestPaths,
          request_deserializer=service__pb2.Empty.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'polkaAutomator.PolkaAutomatorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
